feign:
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000
        loggerLevel: basic
      apiconectorclient:
        url: '${CONECTOR_URL:http://localhost:9002/conector}'
      apiBackendClient:
        url: '${MS_BACKEND_URL:http://localhost:9003}/backend'

management:
  endpoints:
    web:
      base-path: /metrics
      exposure:
        include: "health,info"
server:
  port :  9001
  servlet:
    contextPath: /bff
  ssl:
    enabled: true
    key-store: '${BFF_KEYSTORE:file:///C:/nginx-docker/nginx/ssl/keystore.p12}'
    key-store-type: PKCS12
    key-store-password: '${BFF_KEYSTORE_PASSWORD:changeit}'
    key-alias: bff
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
         issuer-uri: 'http://localhost:8180/realms/dacs'